/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_fpeterek_jnitest_Bridge */

#ifndef _Included_org_fpeterek_jnitest_Bridge
#define _Included_org_fpeterek_jnitest_Bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_fpeterek_jnitest_Bridge
 * Method:    helloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fpeterek_jnitest_Bridge_helloWorld
  (JNIEnv *, jobject);

/*
 * Class:     org_fpeterek_jnitest_Bridge
 * Method:    strlen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_fpeterek_jnitest_Bridge_strlen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_fpeterek_jnitest_Bridge
 * Method:    getAaa
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_fpeterek_jnitest_Bridge_getAaa
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_fpeterek_jnitest_Bridge
 * Method:    goTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_fpeterek_jnitest_Bridge_goTest
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
